version: 2
jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install dependencies
          command: |
            apk add --no-cache \
              py-pip=9.0.0-r1 \
              make
            pip install \
              ansible-tower-cli \
              docker-compose==1.22.0
      - run:
          name: Run docker compose containers
          command: |
            docker-compose -f circleci-docker-compose.yml up -d postgres
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/app.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/app.tar | true
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Build application Docker image
          command: |
            make package
      - run:
          name: Run tests
          command: |
            --docker-compose -f circleci-docker-compose.yml run web npm run migration-up
            --docker-compose -f circleci-docker-compose.yml run web npm run test
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/app.tar company/PROJECT_NAME
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/app.tar
      - run:
          name: Push application Docker image
          command: |
            make tag
            make push
      - deploy:
          name: deploy
          command: |
            echo "write deploy code"
